#!/bin/bash

read -r -d '' asdf << EOM
60% opacity 
60% opacity (without multymedia and browser)
EOM
pkill compton
result=$(echo  "$asdf" | rofi -dmenu "What do you wont to do" -lines 9)

[ "$result" == "60% opacity" ]                                  && compton --config ~/.config/compton.conf
[ "$result" == "60% opacity (without multymedia and browser)" ] && compton --config ~/.config/compton0.conf
exit 0
